version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    image: rynowak/blazing_backend-frontend
    ports:
    - "5000:80"
    depends_on:
      - sql
      - delivery
      - menu
      - orders
    entrypoint: ["./wait-for-it.sh", "sql:1433","-t", "120", "--", "dotnet", "BlazingPizza.Server.dll"]
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      DATA__DIRECTORY: /var/lib/db
      ConnectionStrings__PizzaDatabase: "Server=sql;Initial Catalog=pizza;User Id=sa;Password=yourStrong(!)Password;"
    volumes:
      - data-volume:/var/lib/db
  delivery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.delivery
    image: rynowak/blazing_backend-delivery
    depends_on:
      - redis
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      SERVICE__REDIS: "redis:6379" 
  manager:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.manager
    image: rynowak/blazing_backend-manager
    ports:
    - "5005:80"
    depends_on:
      - delivery
      - orders
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
  menu:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.menu
    image: rynowak/blazing_backend-menu
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      DATA__DIRECTORY: /var/lib/db
      ConnectionStrings__MenuDatabase: "Server=sql;Initial Catalog=menu;User Id=sa;Password=yourStrong(!)Password;"
    depends_on: 
      - sql
    entrypoint: ["./wait-for-it.sh", "sql:1433","-t", "120", "--", "dotnet", "BlazingPizza.MenuService.dll"]
    volumes:
      - data-volume:/var/lib/db
  orders:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.orders
    image: rynowak/blazing_backend-orders
    depends_on:
      - redis
      - sql
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      DATA__DIRECTORY: /var/lib/db
      SERVICE__REDIS: "redis:6379"
      ConnectionStrings__OrdersDatabase: "Server=sql;Initial Catalog=orders;User Id=sa;Password=yourStrong(!)Password;"
    volumes:
      - data-volume:/var/lib/db,
    entrypoint: ["./wait-for-it.sh", "sql:1433","-t", "120", "--", "dotnet", "BlazingPizza.OrderService.dll"]
  redis:
    image: redis
  zipkin:
    image: openzipkin/zipkin
    ports:
    - "9411:9411"
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433"
volumes:
  data-volume: